name: tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, bcmath
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies (Laravel 10)
        run: |
          composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts:^10"
        if: matrix.php >= 8.1 && matrix.php < 8.4

      - name: Execute tests (Laravel 10)
        run: ./vendor/bin/pest --display-deprecations --fail-on-deprecation
        if: matrix.php >= 8.1 && matrix.php < 8.4

      - name: Install dependencies (Laravel 11)
        run: |
          composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts:^11"
        if: matrix.php >= 8.2 && matrix.php <= 8.4

      - name: Execute tests (Laravel 11)
        run: ./vendor/bin/pest --display-deprecations --fail-on-deprecation
        if: matrix.php >= 8.2 && matrix.php <= 8.4

      - name: Install dependencies (Laravel 12)
        run: |
          composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts:^12"
        if: matrix.php >= 8.2 && matrix.php <= 8.4

      - name: Execute tests (Laravel 12)
        run: ./vendor/bin/pest --display-deprecations --fail-on-deprecation
        if: matrix.php >= 8.2 && matrix.php <= 8.4
